<?php

namespace AppBundle\Repository;

/**
 * BestelorderRepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestelorderRepository extends \Doctrine\ORM\EntityRepository
{
}