<?php

namespace AppBundle\Repository;

/**
 * GebruikerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GebruikerRepository extends \Doctrine\ORM\EntityRepository
{
}
