<?php

namespace AppBundle\Repository;

/**
 * klantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class klantRepository extends \Doctrine\ORM\EntityRepository
{
}
