<?php

namespace AppBundle\Repository;

/**
 * OntvangstregelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OntvangstregelRepository extends \Doctrine\ORM\EntityRepository
{
}
