<?php

namespace AppBundle\Repository;

/**
 * productsoortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productsoortRepository extends \Doctrine\ORM\EntityRepository
{
}
