<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJx80xua\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJx80xua/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJx80xua.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJx80xua\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJx80xua\appProdProjectContainer(array(
    'container.build_hash' => 'Jx80xua',
    'container.build_id' => '155d6e11',
    'container.build_time' => 1528108954,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJx80xua');
