<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.user.provider.concrete.in_memory' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\User\\UserProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider.php';

return $this->services['security.user.provider.concrete.in_memory'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider(array('inkoper' => array('password' => 'inkoper', 'roles' => array(0 => 'ROLE_INKOPER')), 'magazijnmeester' => array('password' => 'magazijn', 'roles' => array(0 => 'ROLE_MAGAZIJNMEESTER')), 'administrator' => array('password' => 'administrator', 'roles' => array(0 => 'ROLE_ADMINISTRATOR'))));
