<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDaet5r8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDaet5r8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDaet5r8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDaet5r8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDaet5r8\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Daet5r8',
    'container.build_id' => '5e87026d',
    'container.build_time' => 1528109803,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDaet5r8');
